In [1]:
#question1
'''Python library is a collection of pre-written code modules that provide a set of functionalities to accomplish specific tasks. These modules contain functions, classes, and methods that programmers can use to perform various operations without having to implement them from scratch
We use Python libraries for several reasons:
1.efficiency
2.functionality
3.standardisation etc'''

'Python library is a collection of pre-written code modules that provide a set of functionalities to accomplish specific tasks. These modules contain functions, classes, and methods that programmers can use to perform various operations without having to implement them from scratch\nWe use Python libraries for several reasons:\n1.efficiency\n2.functionality\n3.standardisation etc'

In [2]:
#question2
'''numpy array and python list are both used to store collection of data but they have some key diffrences:
1.data types
2.performance
3.functionality'''

'numpy array and python list are both used to store collection of data but they have some key diffrences:\n1.data types\n2.performance\n3.functionality'

In [3]:
#question3
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
shape=arr.shape
dimension=arr.ndim
size=arr.size
print("shape:",shape)
print("dimension:",dimension)
print("size:",size)

shape: (3, 4)
dimension: 2
size: 12


In [4]:
#question4
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
first_row= arr[0]
print("first row:",first_row)


first row: [1 2 3 4]


In [5]:
#question5
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
element= arr[2,3]
print("Element at the third row and fourth column:", element)




Element at the third row and fourth column: 12


In [6]:
#question6
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
odd_elements = arr[:, 1::2]

print("All odd-indexed elements:")
print(odd_elements)

All odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
#question7
np.random.rand(3,3)

array([[0.77593174, 0.65352304, 0.53701687],
       [0.17417318, 0.18383401, 0.7104364 ],
       [0.98304049, 0.1267292 , 0.52131934]])

In [8]:
#question8
np.random.rand()
'''This function generates random numbers from a uniform distribution over the half-open interval [0, 1).'''

np.random.randn()
'''This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).'''

'This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).'

In [9]:
#Question9
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.expand_dims(arr,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [10]:
#question10
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [11]:
#question11
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

indexwise_multiplication=A*B

matrix_multiplication=np.dot(A, B.T) 

addition=A+B

subtraction=B-A

division=B/A
print("indexwise_multiplication:",indexwise_multiplication)
print("matrix_multiplication:",matrix_multiplication)
print("addition",addition)
print("subtraction:",subtraction)
print("division:",division)

indexwise_multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
matrix_multiplication: [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
addition [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subtraction: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
division: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#question12
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_byteswapped = arr.byteswap()

print("Original array:")
print(arr)
print("\nArray with byte order swapped:")
print(arr_byteswapped)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with byte order swapped:
[[ 72057594037927936 144115188075855872 216172782113783808
  288230376151711744]
 [360287970189639680 432345564227567616 504403158265495552
  576460752303423488]
 [648518346341351424 720575940379279360 792633534417207296
  864691128455135232]]


In [13]:
#question13
'''The np.linalg.inv function in Numpy is used to compute the inverse of a square matrix. The significance of this function lies in its applications in linear algebra, particularly in solving systems of linear equations and in various optimization and estimation problems.'''

'The np.linalg.inv function in Numpy is used to compute the inverse of a square matrix. The significance of this function lies in its applications in linear algebra, particularly in solving systems of linear equations and in various optimization and estimation problems.'

In [14]:
#question14
'''The np.reshape function in Numpy is used to change the shape of an array without changing its data. It allows you to specify the new shape of the array while preserving the total number of elements.'''
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#question14 example
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#question15

'''Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic operations. It enables efficient computation without the need for explicit loop iteration or duplication of data.'''